#cmakedefine LIBXML2_VERSION ${LIBXML2_VERSION}

#cmakedefine PGSQL_VERSION ${PGSQL_NUMERIC_VERSION}

#cmakedefine HAVE_LIBGHT ${HAVE_LIBGHT}

#cmakedefine HAVE_CUNIT ${HAVE_CUNIT}

#cmakedefine PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}"

#cmakedefine POINTCLOUD_VERSION "${POINTCLOUD_VERSION}"
